manifest:  
  remotes:  
    - name: zmkfirmware  
      url-base: https://github.com/zmkfirmware  
    - name: na-ka-no
      url-base: https://github.com
  
  projects:  
    - name: zmk
      remote: zmkfirmware  # ← 本家の安定版リポジトリを参照するように変更
      revision: v0.3       # ← 壊れる前の安定バージョン「v0.3」に完全固定
      import: app/west.yml  
    - name: zmk-pmw3610-driver  
      remote: na-ka-no
      revision: v0.21
  
  self:  
    path: config
